# Generated by Django 4.0.5 on 2022-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_sneakers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_sneakers',
            },
        ),
    ]
