# Generated by Django 4.0.5 on 2022-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_sneakers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'website_sneakers',
            },
        ),
    ]
