# Generated by Django 4.0.5 on 2022-06-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_website_sneakers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_sneakers',
            new_name='MySneakers',
        ),
        migrations.RenameModel(
            old_name='website_sneakers',
            new_name='WebsiteSneakers',
        ),
    ]
